service: hello-world-offline
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: default
  memorySize: 256
  stage: dev
  httpApi:
    payload: "1.0"

plugins:
  - serverless-offline

functions:
  hello-world:
    handler: handler.test
    events:
      - http:
          path: test
          method: get
          cors: true
